### PR TITLE
Frankenstein Ship

### PR DESCRIPTION
**Pull request by HolyTigerGod**

### CODE REVIEW

**Comment by ChuChu42** [comment]
>600 cost
>nanites
>ore silo.and ore redemption
>exosuit fabricator
>NEU

are you shitting me?

**Comment by BBBBAface** [comment]
should be SYN and cost 950 vc - 1150 vc

I'm not a huge fan of the shape either

**Comment by HolyTigerGod** [comment]
> > 600 cost
> > nanites
> > ore silo.and ore redemption
> > exosuit fabricator
> > NEU
> 
> are you shitting me?

There is no ore redemption also fixed the price

**Comment by Addust** [comment]
NEVER pre-spawn an RnD server it glitches the fuck out

**Pull request closed without merging**
